//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/cs_mansionsimpsons-v2.html
gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
models/hostage.mdl
maps/cs_mansionsimpsons-v2.bsp
maps/cs_mansionsimpsons-v2.txt
