//de_westwood_bzc.res created with CtrikeMaps Release v 1.0 by AHBAR
halflife.wad
creditos.wad
texturas_cp2.wad
west.wad
brazuca.wad
gfx/env/2desertup.tga
gfx/env/2desertdn.tga
gfx/env/2desertlf.tga
gfx/env/2desertrt.tga
gfx/env/2desertft.tga
gfx/env/2desertbk.tga
//overviews/de_westwood_bzc.bmp
//overviews/de_westwood_bzc.txt
maps/de_westwood_bzc.bsp
maps/de_westwood_bzc.res
maps/de_westwood_bzc.txt
//models/player/gsg9/gsg9.mdl
//models/player/guerilla/guerilla.mdl
sound/nm_goodbadugly.wav
sound/ambience/guit1.wav
models/cs/personagens/deadgign.mdl
models/cs/personagens/human_suicide.mdl
models/cs/barril/wood_barrel2.mdl
models/cs/animais/hessi_pony02.mdl
models/cs/arvores/plant_cactus.mdl
models/cs/arvores/cactus01.mdl
models/cs/moveis/armario1.mdl
models/cs/moveis/piano.mdl
models/cs/moveis/cm_stool.mdl
models/cs/moveis/bed2.mdl
models/cs/moveis/phono.mdl
models/cs/iluminacao/chandelier.mdl
models/cs/decora/sac.mdl
models/cs/decora/euro.mdl
models/cs/decora/dead_goldbar.mdl
models/cs/decora/lingot_or.mdl
models/cs/decora/moneypiles.mdl
models/cs/alimento/box_misc.mdl
models/cs/alimento/mewok c kaptowkoy.mdl
models/cs/decora/garrafas.mdl
models/cs/moveis/table.mdl
models/cs/props/z_fantana.mdl
models/cs/personagens/steerskull.mdl
models/cs/lixo/lopa.mdl
models/cs/personagens/wanted_3.mdl
models/cs/banheiro/maniak_tualeet.mdl
models/cs/barril/cavetonneaux.mdl
models/cs/decora/armoire14.mdl
models/cs/decora/cama.mdl
models/cs/decora/couchao.mdl
