//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/$10000$.html
halflife.wad
decals.wad
cstrike.wad
cs_dust.wad
cs_assault.wad
cs_office.wad
de_aztec.wad
gfx/env/desbk.tga
gfx/env/desdn.tga
gfx/env/desft.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desup.tga
maps/$10000$.bsp
