//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/gg_simpsons.html
gfx/env/simpsonsbk.tga
gfx/env/simpsonsdn.tga
gfx/env/simpsonsft.tga
gfx/env/simpsonslf.tga
gfx/env/simpsonsrt.tga
gfx/env/simpsonsup.tga
sound/ambience/sweetbeer1.wav
maps/gg_simpsons.bsp
