//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/mini_dust_pro.html
halflife.wad
decals.wad
cstrike.wad
cs_dust.wad
de_aztec.wad
gfx/env/desbk.tga
gfx/env/desdn.tga
gfx/env/desft.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desup.tga
overviews/mini_dust_pro.txt
overviews/mini_dust_pro.bmp
maps/mini_dust_pro.bsp
