gfx/env/cl_desertup.tga
gfx/env/cl_desertdn.tga
gfx/env/cl_desertlf.tga
gfx/env/cl_desertrt.tga
gfx/env/cl_desertft.tga
gfx/env/cl_desertbk.tga
models/hg_industrialzone/toalett.mdl
models/hg_industrialzone/buzz_sat.mdl
models/hg_industrialzone/maniak_tualeet.mdl
models/hg_industrialzone/radio.mdl
models/hg_industrialzone/mafia.mdl
overviews/hg_industrialzone.bmp
overviews/hg_industrialzone.txt
sound/hg_industrialzone/radio_loop.wav
sound/hg_industrialzone/voltage_loop.wav
sound/hg_industrialzone/tunnel_wind_loop.wav
sound/hg_industrialzone/ocean_ambient.wav
sound/hg_industrialzone/water_loop.wav
sound/hg_industrialzone/wind_loop.wav
sound/hg_industrialzone/buzz_loop.wav
sound/hg_industrialzone/factory_loop.wav
sound/hg_industrialzone/vnz_loop.wav
models/hg_industrialzone/bush.mdl
sprites/hg_industrialzone/tv.spr
sprites/laserbeam.spr
